apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: apiconnect.173.193.79.56.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: nodejs-api-service
              servicePort: 32765